# -*- coding: utf-8 -*-
"""HW4 (1) (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eEVSSULZ4T01WZ8EWo9gFyq7_YhLzuy1
"""



# Collaborators: Chandrahaas Mariserla, Ryan Chiang

import csv
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

overwatchData = pd.read_csv("overwatch.csv")

#Question 1

def PickRate(overwatchData):
    heroList = []
    pickRate = []
    for i in range(0, len(overwatchData),8):
        heroList.append(overwatchData.iloc[i,0])
        pickRate.append(overwatchData.iloc[i,3])
    #adding data to two separate lists
    mostPicked = []
    for i in range(0,3):
        mostPicked.append(heroList[pickRate.index(max(pickRate))])
        pickRate.remove(max(pickRate))
        heroList.remove(heroList[pickRate.index(max(pickRate))])
    #adding top 3 played characters to a list
    return mostPicked

print(f"#1 Here are the Top 3 heroes with the highest pick-rate, descending: {PickRate(overwatchData)}.")

#Question 2

def Hit(overwatchData):
    hitlist = []
    hitnum = []
    projlist = []
    projnum = []
    hitscan = 0
    projectile = 0
    #iterating through data to get the name of each hero, as well as the corresponding pick-rate where the tier is titled 'all'. all if/elif statements are for hitscan.
    for i in range(0, len(overwatchData), 8):
        if overwatchData.iloc[i,0] == 'Ana':
            hitlist.append(overwatchData.iloc[i,0])
            hitnum.append(float(overwatchData.iloc[i, 3]))
        elif overwatchData.iloc[i,0] == 'Cassidy':
            hitlist.append(overwatchData.iloc[i,0])
            hitnum.append(float(overwatchData.iloc[i, 3]))
        elif overwatchData.iloc[i,0] == 'Widowmaker':
            hitlist.append(overwatchData.iloc[i,0])
            hitnum.append(float(overwatchData.iloc[i, 3]))
        elif overwatchData.iloc[i,0] == 'Soldier: 76':
            hitlist.append(overwatchData.iloc[i,0])
            hitnum.append(float(overwatchData.iloc[i, 3]))
        elif overwatchData.iloc[i,0] == 'D.Va':
            hitlist.append(overwatchData.iloc[i,0])
            hitnum.append(float(overwatchData.iloc[i, 3]))
        elif overwatchData.iloc[i,0] == 'Ash':
            hitlist.append(overwatchData.iloc[i,0])
            hitnum.append(float(overwatchData.iloc[i, 3]))
        elif overwatchData.iloc[i,0] == 'Tracer':
            hitlist.append(overwatchData.iloc[i,0])
            hitnum.append(float(overwatchData.iloc[i, 3]))
        elif overwatchData.iloc[i,0] == 'Baptiste':
            hitlist.append(overwatchData.iloc[i,0])
            hitnum.append(float(overwatchData.iloc[i, 3]))
        elif overwatchData.iloc[i,0] == 'Sombra':
            hitlist.append(overwatchData.iloc[i,0])
            hitnum.append(float(overwatchData.iloc[i, 3]))
        elif overwatchData.iloc[i,0] == 'Sojourn':
            hitlist.append(overwatchData.iloc[i,0])
            hitnum.append(float(overwatchData.iloc[i, 3]))
        elif overwatchData.iloc[i,0] == 'Junker Queen':
            hitlist.append(overwatchData.iloc[i,0])
            hitnum.append(float(overwatchData.iloc[i, 3]))
        elif overwatchData.iloc[i,0] == 'Bastion':
            hitlist.append(overwatchData.iloc[i,0])
            hitnum.append(float(overwatchData.iloc[i, 3]))
        elif overwatchData.iloc[i,0] == 'Wrecking Ball':
            hitlist.append(overwatchData.iloc[i,0])
            hitnum.append(float(overwatchData.iloc[i, 3]))
        else:
            #if not hitscan, then the other heroes are by logic projectile
            projlist.append(overwatchData.iloc[i, 0])
            projnum.append(float(overwatchData.iloc[i, 3]))
    #takes total of hitscan players pickrate and divides by count of hitscan players, giving hitscan the value of average pickrate

    for i in hitnum:
            hitscan += i
    hitscan = float(hitscan/(len(hitnum)))



    return hitscan

def Proj(overwatchData):
    hitlist = []
    hitnum = []
    projlist = []
    projnum = []
    hitscan = 0
    projectile = 0
    #same iteration for te file above, but to make returning values seprate as there are two functions, we opted to paste the same fucntion but return projectile instead of hitscan
    for i in range(0, len(overwatchData), 8):
        if overwatchData.iloc[i,0] == 'Ana':
            hitlist.append(overwatchData.iloc[i,0])
            hitnum.append(float(overwatchData.iloc[i, 3]))
        elif overwatchData.iloc[i,0] == 'Cassidy':
            hitlist.append(overwatchData.iloc[i,0])
            hitnum.append(float(overwatchData.iloc[i, 3]))
        elif overwatchData.iloc[i,0] == 'Widowmaker':
            hitlist.append(overwatchData.iloc[i,0])
            hitnum.append(float(overwatchData.iloc[i, 3]))
        elif overwatchData.iloc[i,0] == 'Soldier: 76':
            hitlist.append(overwatchData.iloc[i,0])
            hitnum.append(float(overwatchData.iloc[i, 3]))
        elif overwatchData.iloc[i,0] == 'D.Va':
            hitlist.append(overwatchData.iloc[i,0])
            hitnum.append(float(overwatchData.iloc[i, 3]))
        elif overwatchData.iloc[i,0] == 'Ash':
            hitlist.append(overwatchData.iloc[i,0])
            hitnum.append(float(overwatchData.iloc[i, 3]))
        elif overwatchData.iloc[i,0] == 'Tracer':
            hitlist.append(overwatchData.iloc[i,0])
            hitnum.append(float(overwatchData.iloc[i, 3]))
        elif overwatchData.iloc[i,0] == 'Baptiste':
            hitlist.append(overwatchData.iloc[i,0])
            hitnum.append(float(overwatchData.iloc[i, 3]))
        elif overwatchData.iloc[i,0] == 'Sombra':
            hitlist.append(overwatchData.iloc[i,0])
            hitnum.append(float(overwatchData.iloc[i, 3]))
        elif overwatchData.iloc[i,0] == 'Sojourn':
            hitlist.append(overwatchData.iloc[i,0])
            hitnum.append(float(overwatchData.iloc[i, 3]))
        elif overwatchData.iloc[i,0] == 'Junker Queen':
            hitlist.append(overwatchData.iloc[i,0])
            hitnum.append(float(overwatchData.iloc[i, 3]))
        elif overwatchData.iloc[i,0] == 'Bastion':
            hitlist.append(overwatchData.iloc[i,0])
            hitnum.append(float(overwatchData.iloc[i, 3]))
        elif overwatchData.iloc[i,0] == 'Wrecking Ball':
            hitlist.append(overwatchData.iloc[i,0])
            hitnum.append(float(overwatchData.iloc[i, 3]))
        else:
            projlist.append(overwatchData.iloc[i, 0])
            projnum.append(float(overwatchData.iloc[i, 3]))
    # does the same as the above function, but returns projectile
    for i in projnum:
            projectile += i

    projectile = float(projectile/(len(projnum)))



    return projectile

print(f"#2 AVG Hit-scan Hero Pick-Rate: {Hit(overwatchData):.2f}% and AVG Projectile Hero Pick Rate: {Proj(overwatchData):.2f}%.")


#QUESTION 3

def ElimRate(overwatchData):
    #similar to our first function, now trying to search for a different value for each hero thus the change in what we append to list.
    heroList = []
    elimRate = []
    for i in range(0, len(overwatchData),8):
        heroList.append(overwatchData.iloc[i,0])
        elimRate.append(overwatchData.iloc[i,5])
    #adding data to two separate lists
    mostElims = []
    for i in range(0,3):
        mostElims.append(heroList[elimRate.index(max(elimRate))])
        elimRate.remove(max(elimRate))
        heroList.remove(heroList[elimRate.index(max(elimRate))])
    #adding highest 3 elimination rate characters to a list
    return mostElims

print(f"#3 The 3 heroes associated with the highest elimination rate, descending, are:{ElimRate(overwatchData)}.")




#QUESTION 4


winrate_dict = {}
winrate_dict['Ana'] = 3
list = ['bob', 'lob']
for i in range(1, len(overwatchData), 8):
    winrate_dict[overwatchData.iloc[i,0]] = []
    winrate_dict[overwatchData.iloc[i,0]].append(overwatchData.iloc[i,4])
    #searching for bronze tier values, appending to the list created to hold multiple values for the hero key
for i in range(7, len(overwatchData), 8):
    #searching for grandmaster values, to append to key
    winrate_dict[overwatchData.iloc[i,0]].append(overwatchData.iloc[i,4])

x = []
y = []
for key in winrate_dict.keys():
    x.append(key)
    y.append(winrate_dict[key])

# Created legend in this manner as dictionary created to store heroes and the win rate of both tiers in nested lists, the label of what tier is what gave us trouble in creating a legend depsite trying plt.legend()
print("-------------------------------------")
print("               LEGEND                ")
print("                ~~~~                 ")
print("    GrandMaster WinRate : Orange     ")
print("                                     ")
print("     Bronze Tier WinRate : Blue      ")
print("                                     ")
print("-------------------------------------")
plt.figure(figsize=[40,6])
plt.plot(x, y)
plt.title("Win-Rates per Hero: Bronze vs GrandMaster Skill Tier", fontsize = 30)
plt.xlabel("Hero", fontsize = 19)
plt.ylabel("Win-Rate in Percent", fontsize = 20)



#plot for most elims question ( num4)

"""-> Chandrahaas Mariserla, Ryan Chiang


Our Dataset concerns player data from Overwatch 2, Season 1.

Which heroes had the highest average pick rate across all ranks?
The top 3 heroes with the highest average pick rate are: Ana, Moira, Genji - in order from least to greatest. This indicates that out of 36 unique heroes in the data file, the 3 heroes most likely to be chosen for play are Ana, Moira, and Genji. The top two are in the support role in the game. This is not necessarily surprising since from experience support has been a more popular role to play ingame. What was surprising was that Genji, a damage hero, was in the top 3 of most popular characters.

Which Hero did players prefer - hit scan or projectile?
In FPS games, there are two main systems to register when something is hit. These are hitscan, and projectile. In game, hitscan is where the game checks where you are aiming as you fire and sees if there is a target. Projectile has a travel time before it can register the hit. Overwatch is unique in that it has both hitscan characters and projectile characters. To calculate if each was more used, we took the average of the average pick rate for each projectile hero and compared it to the average of the average pick rate for each hitscan hero. Players picked hitscan heroes at an average rate of 3.05% Players picked projectile heroes at an average rate of 2.74%. There is a slightly higher rate of players choosing hitscan characters, however the difference is close enough that there could not be a statistically significant difference.

What characters are more successful in low rank lobbies(Bronze) and high rank lobbies?
Examining the difference in win rates between the highest rank and the lowest rank can show which characters are more dominant in low rank lobbies and high rank lobbies. It can show us which characters are more easy to learn and do well versus which ones are harder to master. For example, the hero Wrecking Ball is known to be extremely hard to learn. This is confirmed with low rank lobbies having a win rate of 29.86% and with high ranks at a rate of 35.36%.

Which heroes have the highest average elimination rate /10 min (10 minute measured playtime)?
The top 3 characters with the highest average elimination rate are D.Va, Pharah, and Symmetra. This indicates players are most able to confirm kills with these characters. D.Va has high mobility in game and is able to chase, and focus on enemy players. Pharah is a flying character and as a result can be hard to deal with by the enemy team. Symmetra being in the third position was very interesting. The way she does damage is that as her ranged beam is aimed on a target, her damage increases over time, using 3 levels of damage. But, because her first damage level is very weak, this results in her being a type of glass cannon. She has to get very close and it can take a significant amount of time to charge to the highest level, As a result she can be quickly eliminated.

"""